channels:
- conda-forge
- bioconda
- defaults
dependencies:
- snakemake = 8.26.0
- dRep = 3.4.5
- checkm-genome 1.2.3

general:
  data: "data"
  number_of_bins: 2
  output_dir: "output_dir"
wildcards:
  read:
  - 1
  - 2
  sample:
  - "SRR12324251"
  - "SRR23604272"
